#!/bin/bash
####################
#
# ©Credit X-UI lates version by Gozargah
# github https://github.com/Gozargah/
# Modifed multiport by CyberVPN
#
#####################
echo "Setup X-UI marzban multiport reserve nginx"

sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install
sudo apt install nginx -y
